version: "3"

services:

  node1:
    build: .
    env_file:
      - .env
    container_name: node1
    volumes:
      - .:/app
    ports:
      - "9001:9000"
    environment:
      ROLE: client
      CLIENT_ID: client1
      CLIENT_PORT: 9000
      PRIMARY: node2:8000
      REPLICAS: node2:8000,node3:8000,node4:8000,node5:8000

  node2:
    build: .
    env_file:
      - .env
    container_name: node2
    ipc: host
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    environment:
      ROLE: replica
      AGENT_SOCKET_PATH: /tmp/agent.sock
      PORT: 8000
      NODE_ID: node2
      CLIENT_ADDR: node1:9000
      PEERS: node2:8000,node3:8000,node4:8000,node5:8000
      MODEL_NAME: qwen/qwen2.5-0.5b-instruct
      SGLANG_BASE_URL: http://127.0.0.1:30000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]

  node3:
    build: .
    env_file:
      - .env
    container_name: node3
    ipc: host
    volumes:
      - .:/app
    ports:
      - "8003:8000"
    environment:
      ROLE: replica
      AGENT_SOCKET_PATH: /tmp/agent.sock
      PORT: 8000
      NODE_ID: node3
      CLIENT_ADDR: node1:9000
      PEERS: node2:8000,node3:8000,node4:8000,node5:8000
      MODEL_NAME: qwen/qwen2.5-0.5b-instruct
      SGLANG_BASE_URL: http://127.0.0.1:30000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [gpu]

  node4:
    build: .
    env_file:
      - .env
    container_name: node4
    ipc: host
    volumes:
      - .:/app
    ports:
      - "8004:8000"
    environment:
      ROLE: replica
      AGENT_SOCKET_PATH: /tmp/agent.sock
      PORT: 8000
      NODE_ID: node4
      CLIENT_ADDR: node1:9000
      PEERS: node2:8000,node3:8000,node4:8000,node5:8000
      MODEL_NAME: qwen/qwen2.5-0.5b-instruct
      SGLANG_BASE_URL: http://127.0.0.1:30000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["2"]
              capabilities: [gpu]

  node5:
    build: .
    env_file:
      - .env
    container_name: node5
    ipc: host
    volumes:
      - .:/app
    ports:
      - "8005:8000"
    environment:
      ROLE: replica
      AGENT_SOCKET_PATH: /tmp/agent.sock
      PORT: 8000
      NODE_ID: node5
      CLIENT_ADDR: node1:9000
      PEERS: node2:8000,node3:8000,node4:8000,node5:8000
      MODEL_NAME: qwen/qwen2.5-0.5b-instruct
      SGLANG_BASE_URL: http://127.0.0.1:30000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["3"]
              capabilities: [gpu]
