version: "3"

services:

  node1:
    build: .
    env_file:
      - .env
    container_name: node1
    volumes:
      - .:/app
    ports:
      - "8001:8000"
      - "9001:9000"
    environment:
      PORT: 8000
      NODE_ID: 1
      PEERS: node1:8000,node2:8000,node3:8000,node4:8000,node5:8000

      CLIENT_ID: 1
      CLIENT_PORT: 9000
      PRIMARY: node2:8000
      REPLICAS: node1:8000,node2:8000,node3:8000,node4:8000,node5:8000

  node2:
    build: .
    env_file:
      - .env
    container_name: node2
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    environment:
      AGENT_SOCKET_PATH: /tmp/agent.sock
      PORT: 8000
      NODE_ID: 2
      PEERS: node1:8000,node2:8000,node3:8000,node4:8000,node5:8000

  node3:
    build: .
    env_file:
      - .env
    container_name: node3
    volumes:
      - .:/app
    ports:
      - "8003:8000"
    environment:
      AGENT_SOCKET_PATH: /tmp/agent.sock
      PORT: 8000
      NODE_ID: 3
      PEERS: node1:8000,node2:8000,node3:8000,node4:8000,node5:8000

  node4:
    build: .
    env_file:
      - .env
    container_name: node4
    volumes:
      - .:/app
    ports:
      - "8004:8000"
    environment:
      AGENT_SOCKET_PATH: /tmp/agent.sock
      PORT: 8000
      NODE_ID: 4
      PEERS: node1:8000,node2:8000,node3:8000,node4:8000,node5:8000

  node5:
    build: .
    env_file:
      - .env
    container_name: node5
    volumes:
      - .:/app
    ports:
      - "8005:8000"
    environment:
      AGENT_SOCKET_PATH: /tmp/agent.sock
      PORT: 8000
      NODE_ID: 5
      PEERS: node1:8000,node2:8000,node3:8000,node4:8000,node5:8000