# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rag import rag_pb2 as rag_dot_rag__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rag/rag_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RagServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/rag.RagService/Ping',
                request_serializer=rag_dot_rag__pb2.RagPingRequest.SerializeToString,
                response_deserializer=rag_dot_rag__pb2.RagPingReply.FromString,
                _registered_method=True)
        self.RouteQuery = channel.unary_unary(
                '/rag.RagService/RouteQuery',
                request_serializer=rag_dot_rag__pb2.RouteQueryRequest.SerializeToString,
                response_deserializer=rag_dot_rag__pb2.RouteQueryReply.FromString,
                _registered_method=True)
        self.SendEvidence = channel.unary_unary(
                '/rag.RagService/SendEvidence',
                request_serializer=rag_dot_rag__pb2.SendEvidenceRequest.SerializeToString,
                response_deserializer=rag_dot_rag__pb2.SendEvidenceReply.FromString,
                _registered_method=True)


class RagServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RouteQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendEvidence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RagServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=rag_dot_rag__pb2.RagPingRequest.FromString,
                    response_serializer=rag_dot_rag__pb2.RagPingReply.SerializeToString,
            ),
            'RouteQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteQuery,
                    request_deserializer=rag_dot_rag__pb2.RouteQueryRequest.FromString,
                    response_serializer=rag_dot_rag__pb2.RouteQueryReply.SerializeToString,
            ),
            'SendEvidence': grpc.unary_unary_rpc_method_handler(
                    servicer.SendEvidence,
                    request_deserializer=rag_dot_rag__pb2.SendEvidenceRequest.FromString,
                    response_serializer=rag_dot_rag__pb2.SendEvidenceReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rag.RagService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rag.RagService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RagService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/Ping',
            rag_dot_rag__pb2.RagPingRequest.SerializeToString,
            rag_dot_rag__pb2.RagPingReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RouteQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/RouteQuery',
            rag_dot_rag__pb2.RouteQueryRequest.SerializeToString,
            rag_dot_rag__pb2.RouteQueryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendEvidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/SendEvidence',
            rag_dot_rag__pb2.SendEvidenceRequest.SerializeToString,
            rag_dot_rag__pb2.SendEvidenceReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
