# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\"\x0f\n\rHealthRequest\".\n\x0bHealthReply\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"/\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\"<\n\tTaskReply\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t2x\n\x0c\x41gentService\x12\x37\n\x0bHealthCheck\x12\x14.agent.HealthRequest\x1a\x12.agent.HealthReply\x12/\n\x07RunTask\x12\x12.agent.TaskRequest\x1a\x10.agent.TaskReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=22
  _globals['_HEALTHREQUEST']._serialized_end=37
  _globals['_HEALTHREPLY']._serialized_start=39
  _globals['_HEALTHREPLY']._serialized_end=85
  _globals['_TASKREQUEST']._serialized_start=87
  _globals['_TASKREQUEST']._serialized_end=134
  _globals['_TASKREPLY']._serialized_start=136
  _globals['_TASKREPLY']._serialized_end=196
  _globals['_AGENTSERVICE']._serialized_start=198
  _globals['_AGENTSERVICE']._serialized_end=318
# @@protoc_insertion_point(module_scope)
