# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: network.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'network.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rnetwork.proto\x12\x07network\"\x1d\n\x0bPingRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\",\n\tPingReply\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"-\n\x0eMessageRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x1e\n\x0cMessageReply\x12\x0e\n\x06status\x18\x01 \x01(\t2\x81\x01\n\x0eNetworkService\x12\x30\n\x04Ping\x12\x14.network.PingRequest\x1a\x12.network.PingReply\x12=\n\x0bSendMessage\x12\x17.network.MessageRequest\x1a\x15.network.MessageReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=26
  _globals['_PINGREQUEST']._serialized_end=55
  _globals['_PINGREPLY']._serialized_start=57
  _globals['_PINGREPLY']._serialized_end=101
  _globals['_MESSAGEREQUEST']._serialized_start=103
  _globals['_MESSAGEREQUEST']._serialized_end=148
  _globals['_MESSAGEREPLY']._serialized_start=150
  _globals['_MESSAGEREPLY']._serialized_end=180
  _globals['_NETWORKSERVICE']._serialized_start=183
  _globals['_NETWORKSERVICE']._serialized_end=312
# @@protoc_insertion_point(module_scope)
