# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: network.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'network.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rnetwork.proto\x12\x07network\"\x1d\n\x0bPingRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\",\n\tPingReply\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"-\n\x0eMessageRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x1e\n\x0cMessageReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"\xca\x01\n\x0fProtocolMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x30\n\x0e\x63lient_request\x18\x02 \x01(\x0b\x32\x16.network.ClientRequestH\x00\x12\x32\n\x0fordered_request\x18\x03 \x01(\x0b\x32\x17.network.OrderedRequestH\x00\x12\x36\n\x11speculative_reply\x18\x04 \x01(\x0b\x32\x19.network.SpeculativeReplyH\x00\x42\t\n\x07payload\"Y\n\rClientRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x0e\n\x06prompt\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\"\xbf\x01\n\x0eOrderedRequest\x12.\n\x0e\x63lient_request\x18\x01 \x01(\x0b\x32\x16.network.ClientRequest\x12\x0c\n\x04view\x18\x02 \x01(\x05\x12\r\n\x05seqno\x18\x03 \x01(\x05\x12\x16\n\x0erequest_digest\x18\x04 \x01(\t\x12\x16\n\x0ehistory_digest\x18\x05 \x01(\t\x12\x1d\n\x15nondeterministic_data\x18\x06 \x01(\t\x12\x11\n\tleader_id\x18\x07 \x01(\t\"\xdb\x01\n\x10SpeculativeReply\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x0c\n\x04view\x18\x03 \x01(\x05\x12\r\n\x05seqno\x18\x04 \x01(\x05\x12\x16\n\x0ehistory_digest\x18\x05 \x01(\t\x12\x15\n\rresult_digest\x18\x06 \x01(\t\x12\x12\n\nreplica_id\x18\x07 \x01(\t\x12\x0e\n\x06result\x18\x08 \x01(\t\x12\x30\n\x0fordered_request\x18\t \x01(\x0b\x32\x17.network.OrderedRequest2\x8c\x01\n\x0eNetworkService\x12\x30\n\x04Ping\x12\x14.network.PingRequest\x1a\x12.network.PingReply\x12H\n\x15HandleProtocolMessage\x12\x18.network.ProtocolMessage\x1a\x15.network.MessageReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=26
  _globals['_PINGREQUEST']._serialized_end=55
  _globals['_PINGREPLY']._serialized_start=57
  _globals['_PINGREPLY']._serialized_end=101
  _globals['_MESSAGEREQUEST']._serialized_start=103
  _globals['_MESSAGEREQUEST']._serialized_end=148
  _globals['_MESSAGEREPLY']._serialized_start=150
  _globals['_MESSAGEREPLY']._serialized_end=180
  _globals['_PROTOCOLMESSAGE']._serialized_start=183
  _globals['_PROTOCOLMESSAGE']._serialized_end=385
  _globals['_CLIENTREQUEST']._serialized_start=387
  _globals['_CLIENTREQUEST']._serialized_end=476
  _globals['_ORDEREDREQUEST']._serialized_start=479
  _globals['_ORDEREDREQUEST']._serialized_end=670
  _globals['_SPECULATIVEREPLY']._serialized_start=673
  _globals['_SPECULATIVEREPLY']._serialized_end=892
  _globals['_NETWORKSERVICE']._serialized_start=895
  _globals['_NETWORKSERVICE']._serialized_end=1035
# @@protoc_insertion_point(module_scope)
